### PR TITLE
Fix errors introduced by next.js updates

### PR DESCRIPTION
**Pull request by thethomaseffect**
There were a number of warnings and errors when I ran Nitro in dev mode which I have addressed below.

- The `.now` folder has been replaced by the `.vercel`
- `static` has been renamed `public`, and the prefix no longer need to be included in paths
- `routes` config has been split up into different types and headers has been given its own top-level property. src and desc have been renamed to their full English versions.
- The `vercel` package has been added as a development dependency and the `dev` script now uses it instead of `now`
- The viewport meta tag was moved to the `pages/_app.tsx` file as advised
- `pages/_document.tsx` now uses the Html react component rather than the old bare html tag.
- The external path to the material-ui logo has been fixed to use the latest.
- Any paths referencing the old static folder have been fixed.

There were some dependencies that could be updated (and removed in the case of many of the @types packages as they are now included with the associated packages) but I figured this PR was big enough and you appear to have a bot for dependencies. Let me know if anything needs changing!

### CODE REVIEW

**Comment by williamluke4** [comment]
Hey @thethomaseffect, thanks for this. It seems to be failing because of this 
```
Failed to compile.
--
14:14:46.253 | Entry module not found: Error: Can't resolve './sw.js' in '/vercel/workpath0'
14:14:46.253 | > Build error occurred
14:14:46.254 | Error: > Build failed because of webpack errors
14:14:46.254 | at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)

```

**Comment by thethomaseffect** [comment]
Ah I see, I didn't test everything in production mode! Shouldn't take long to fix 👍

**Comment by williamluke4** [comment]
Thanks @thethomaseffect

**Comment by thethomaseffect** [comment]
Thank you, this boilerplate was just the right amount of complex to start my new project 😊

**Comment by williamluke4** [comment]
Glad that it helped

**Pull request merged**
